[package]
name = "rslidar-reader"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
ctrlc.workspace = true
zenoh = { version = "1.10", features = ["shared-memory", "unstable"] }
pcap-file = "2"
nalgebra = "..."   # pin a version; "*" won't fly in a shared workspace

